services:
  prod_postgres:
    profiles: [prod]
    image: postgres:18.1
    container_name: xoby_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
      LANG: "en_US.utf8"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
    command:
      - "postgres"

  test_postgres:
    profiles: [test]
    image: postgres:18.1
    container_name: xoby_testing_db
    restart: always
    env_file: ".testing.env"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
      LANG: "en_US.utf8"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - test_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"

  redis:
    profiles: [prod]
    image: redis:latest
    container_name: xoby_redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  test_redis:
    profiles: [test]
    image: redis:latest
    container_name: test_xoby_redis
    restart: always
    env_file: ".testing.env"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - test_redis_data:/data

volumes:
  pgdata:
  test_pgdata:
  redis_data:
  test_redis_data:
